### ISSUE TITLE
broken image link for the ssh

### ISSUE THREAD

**Issue by Milokita** [cuhk-haosun/doc-manual-pub#2]
The image does not show up for the document https://github.com/cuhk-haosun/doc-manual-pub/tree/main/SSH

would you mind fixing the link? @HoshinoKyouna 

I'd recommend relative path for the images

**Comment by HoshinoKyouna** [comment]
I will handle this as soon as possible.

**Comment by Milokita** [comment]
finished
https://github.com/cuhk-haosun/doc-manual-pub/pull/4
